---
- name: Getting Started First Playbook Extended
  hosts: local
  gather_facts: true
  tasks:

    - name: Create local folder for downloads
      file:
        path: /opt/test
        state: directory
        mode: 0777

    - name: print to file
      shell:
        cmd: echo "hello" > /opt/test/hello.txt
