---
- name: Getting Started First Playbook Extended
  hosts: localhost
  gather_facts: true
  become: true
  tasks:

    - name: Create local folder for downloads
      file:
        path: /opt/test
        state: directory
        mode: 0777

    - name: print to file
      shell:
        cmd: echo "hello" > "/opt/test/{{ co_name }}.txt"
